### PR TITLE
Biodata a

### PR DESCRIPTION
**Pull request by astawan**
Fiture biodata A

### CODE REVIEW

**Comment by astawan** [comment]
ini salah bro

**Comment by NoPlayerCharacter** [comment]
> ini salah bro @NoPlayerCharacter

Ok pak

**Comment by astawan** [comment]
fixed in [aef4857](https://github.com/astawan/biodata/pull/1/commits/aef4857aa965a34249d532c17055ce77c04137dc)

**Comment by NoPlayerCharacter** [comment]
> fixed in [aef4857](https://github.com/astawan/biodata/pull/1/commits/aef4857aa965a34249d532c17055ce77c04137dc)

**Comment by astawan** [comment]
ternyata masih ada yang kurang @NoPlayerCharacter

**Pull request merged**
